name: Alwaysdata Login Test

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */12 * * *'

jobs:
  login:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          ALWAYSDATA_USER: ${{ secrets.ALWAYSDATA_USER }}
          ALWAYSDATA_PASS: ${{ secrets.ALWAYSDATA_PASS }}
        run: |
          python login.py
